#!/sbin/sh

. "$env"

print "Installing ramdisk..."

cd $tmp/ramdisk

rm -f init
cp $tmp/ramdiskres/init ./
chmod 0755 init

rm -f init.environ.rc
cp $tmp/ramdiskres/init.environ.rc ./
chmod 0755 init.environ.rc

rm -rf init.oem_ftm.rc
cp $tmp/ramdiskres/init.oem_ftm.rc
chmod 0755 init.oem_ftm.rc

rm -f init.rc
cp $tmp/ramdiskres/init.rc ./
chmod 0755 init.rc

rm -f init.usb.configfs.rc
cp $tmp/ramdiskres/init.usb.configfs.rc ./
chmod 0755 init.usb.configfs.rc

rm -f init.usb.rc
cp $tmp/ramdiskres/init.usb.rc ./
chmod 0755 init.usb.rc

rm -f init.zygote32.rc
cp $tmp/ramdiskres/init.zygote32.rc ./
chmod 0755 init.zygote32.rc

rm -f init.zygote64_32.rc
cp $tmp/ramdiskres/init.zygote64_32.rc ./
chmod 0755 init.zygote64_32.rc

rm -f ueventd.rc
cp $tmp/ramdiskres/ueventd.rc ./
chmod 0755 ueventd.rc

exit 0
